export const ADD_FAVORITE_CITY = "ADD_FAVORITE_CITY";
export const REMOVE_FAVORITE_CITY = "REMOVE_FAVORITE_CITY";
export const REMOVE_FAVORITE_CITY_FROM_FAVORITES = "REMOVE_FAVORITE_CITY_FROM_FAVORITES";
export const FETCH_FAVORITE_CITY = "FETCH_FAVORITE_CITY";
export const INIT_FAVORITES_CITIES = "INIT_FAVORITES_CITIES";
export const ADD_INFO_CITY_TO_FAVORITES = 'ADD_INFO_CITY_TO_FAVORITES';

export const UPDATE_FORECAST_FIVE_DAYS = 'GET_FORECAST_FIVE_DAY';
export const UPDATE_IS_LIKE = 'UPDATE_IS_LIKE';
export const INITAL_DEFUALT_CITY_WITH_GEOLOCATION = 'INITAL_DEFUALT_CITY_WITH_GEOLOCATION';